version: '3.7'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      # - PGHOST='localhost'
      # - PGUSER=process.env.POSTGRES_USER
      # - PGDATABASE=jpbscheduler
      # - PGPASSWORD=postgres
      # - PGPORT=5438
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5438:5432'
    volumes:
      #- ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create databse and tables
      - ./server/sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
